trigger: none
pool: amiteshpool
stages:
- stage: TerraformInstall
  jobs:
  - job: TerraformInstallJob
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
- stage: TFSec
  jobs:
  - job: TFSecJob
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
